/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { useStore } from './zusStore';

export default function Model(props) {
	const group = useRef();
	const { position } = props;
	const width = useStore((state) => state.width);
	// const newDrawers = useStore((state) => state.adjustDrawers);
	// const drawer = useStore((state) => state.drawer);

	console.log('model component', position);
	// const divsX = useStore((state)=> state.width)
	const { nodes, materials } = useLoader(GLTFLoader, '/drawer.gltf');
	console.log('nodes', nodes);

	return (
		<group
			ref={group}
			{...props}
			dispose={null}
			position={position}
			// onClick={newDrawers([0, 0, 0])}
		>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid1.geometry}
			/>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid2.geometry}
			/>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid3.geometry}
			/>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid4.geometry}
			/>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid5.geometry}
			/>
			<mesh
				material={materials['191,191,191']}
				geometry={nodes.Solid6.geometry}
			/>
		</group>
	);
}
